version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/codacy/pulse-event-cli/internal/build.Version={{.Version}} -X github.com/codacy/pulse-event-cli/internal/build.Date={{time "2006-01-02"}}
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers_v2:
  - images:
      - "codacy/pulse-event-cli"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major}}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "latest"
