builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-prerelease"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
