builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/codacy/pulse-event-cli/internal/build.Version={{.Version}} -X github.com/codacy/pulse-event-cli/internal/build.Date={{time "2006-01-02"}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - binaries:
    - pulse-event-cli
    image_templates:
    - "codacy/pulse-event-cli:{{ .Tag }}"
    - "codacy/pulse-event-cli:v{{ .Major }}"
    - "codacy/pulse-event-cli:v{{ .Major }}.{{ .Minor }}"
    - "codacy/pulse-event-cli:latest"
