name: Pulse

on:
  push:
    branches: ["github-action"]

jobs:
  pulse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
            # Will fetch all history and tags required to generate version
            fetch-depth: 0
      - name: "Push data to pulse"
        uses: ./